name: 'Incus Launch VM Action'
description: 'Launches an Incus VM on a remote server'
author: 'Nubificus LTD'
branding:
  icon: 'box'
  color: 'blue'

inputs:
  vm_name:
    description: 'Name of the VM'
    required: true
  vm_description:
    description: 'Description of the VM'
    required: false
  incus_remote:
    description: 'Name of the Incus remote'
    required: true
  incus_image:
    description: 'Name of the Incus image'
    required: false
    default: 'images:ubuntu/22.04/cloud'
  cpu_cores:
    description: 'Number of CPU cores'
    required: false
    default: '1'
  memory:
    description: 'Amount of memory in GiB'
    required: false
    default: '2'
  disk_size:
    description: 'Size of the disk in GiB'
    required: false
    default: '10'
  incus_profile:
    description: 'Name of the Incus profile'
    required: false
    default: 'default'
  incus_project:
    description: 'Name of the Incus project'
    required: false
    default: 'default'
  cleanup:
    description: 'Whether to cleanup the VM after the action'
    required: false
    default: 'false'
  snapshot:
    description: 'Whether to create a snapshot of the VM'
    required: false
    default: 'false'

outputs:
  incus_vm_ip:
    description: 'IP address of the launched Incus VM'
  snapshot_id:
    description: 'ID of the created snapshot'

runs:
  using: 'node20'
  main: 'src/launch.js'
  post: 'src/cleanup.js'
